alias o='xdg-open'
alias r='source /usr/bin/ranger'
alias mv='mv -i'
alias rm='rm -i'
alias books='cd ~/Documents/books'
alias school='cd ~/Documents/school'
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."
